Statistic View Page
nhan0504/CS326 pull request #14
Opened 2024-10-29 20:39 UTC by nhan0504

# What
- Created the Statistic Page with 5 charts:
    - Bar chart for top 5 most worn items
    - Bar chart for items worn less than 2 times
    - Calculate and display cost per wear for each item
    - Doughnut chart for wear frequency of items in each category
    - Pie chart for number of items in each category
- Use chart.js library to create charts
- Populate `wardrobeItems` with TestData

# Testing done
- Run `npm run start` to view the stats page

![image](https://github.com/user-attachments/assets/647e1753-685b-4f3c-bc41-7520c2e6528f)
![image](https://github.com/user-attachments/assets/e4a6b0f3-8ffb-44f0-b46c-ac1dfab74136)

# Note
- Statistic is displayed based on test data. Will integrate with the indexedDb once the service is ready.

2024-10-29 21:36 UTC, sophia-hubscher requested changes
This is so so cool!! I love the charts! I left a few little comments, but once those are addressed, I think it's ready to merge

2024-10-29 21:36 UTC, sophia-hubscher commented on src/components/StatsViewComponent/StatsViewComponent.js
> +  async loadWardrobeItems() {
This getTestWardrobeItems function is called synchronously, so I think you can omit the async keyword

2024-10-29 21:36 UTC, sophia-hubscher commented on src/components/StatsViewComponent/StatsViewComponent.js
> +  renderPieChart(containerId, labels, data) {
Your render chart functions have a lot of repeated code—it might be easier to just do one renderChart function with a type input (bar, doughnut, or pie) so when you change one function you don't have to remember to go in and change the other two too

2024-10-29 21:36 UTC, sophia-hubscher commented on src/components/StatsViewComponent/StatsViewComponent.js
> +  renderPieChart(containerId, labels, data) {
Like as an example you could call it like this

```
this.renderChart('mostWornChart', mostWornLabels, mostWornData, 'Times Worn', 'bar');
this.renderChart('wearByCategoryChart', categoryLabels, categoryValues, null, 'doughnut');
```

2024-10-29 21:36 UTC, sophia-hubscher commented on src/components/StatsViewComponent/StatsViewComponent.js
> +    setTimeout(() => {
This is _super_ picky, but requestAnimationFrame might be mildly better than setTimeout, although I doubt it'll really make all that big of a difference

2024-10-29 21:40 UTC, sophia-hubscher commented
Oops just noticed this! Our site is supposed to be responsive, so it might be worth messing around with the CSS a bit more to make sure it functions on all screen sizes.

<img width="523" alt="Screen Shot 2024-10-29 at 5 37 31 PM" src="https://github.com/user-attachments/assets/fc3b0427-4546-40ab-8eee-c4849fb38477">

My first instinct would be to use `@media (max-width: somenumber px) {}` and to stack everything vertically when the screen is narrow enough. You might also want to add more text wrapping. That should probably clear things up though.

2024-10-30 15:49 UTC, nhan0504 commented on src/components/StatsViewComponent/StatsViewComponent.js
> +    setTimeout(() => {
It didn't make any difference when I made the change, but I still changed it to `requestAnimationFrame`

2024-10-30 15:54 UTC, nhan0504 commented on src/components/StatsViewComponent/StatsViewComponent.js
> +  async loadWardrobeItems() {
I put it as async function because in the future I will use that function to get all items from indexedDB. Right now, it might not make sense for dummy data but will integrate with indexedDB

2024-10-30 16:21 UTC, sophia-hubscher commented on src/components/StatsViewComponent/StatsViewComponent.js
> +  renderPieChart(containerId, labels, data) {
Ok, gotcha! I see why the bar chart is separate. The pie and doughnut charts are almost identical though, no?

2024-10-30 16:24 UTC, sophia-hubscher approved these changes
Love it! Looks great!

2024-10-30 16:24 UTC, merged