merge logbranch with main
nhan0504/CS326 pull request #42
Opened 2024-11-12 03:57 UTC by hungumass

This is basically logbranch merged with main. Created a new branch for easy modification (Sophia's suggestion :D)

2024-11-12 16:32 UTC, sophia-hubscher requested changes
Looks good! I left one comment about the favorite icon that is worth taking a look at. Also, I assume

2024-11-12 16:32 UTC, sophia-hubscher commented on front-end/src/components/LogViewComponent/LogViewComponent.js
> +    heartIcon.classList.add("favorite-icon");
Because this class name is used elsewhere, when you update the CSS to make this larger, it messes with the wardrobe page. My suggested fix would be to just use a new class name or to remove the styling that increases the size of favorite-icon

<img width="1552" alt="Screen Shot 2024-11-12 at 11 28 30 AM" src="https://github.com/user-attachments/assets/5ebcbb01-d7f1-4d26-8bc9-e92b612902a5">

2024-11-12 16:32 UTC, sophia-hubscher commented on front-end/src/components/LogViewComponent/LogViewComponent.js
> +import { getTestOutfits,getTestWardrobeItems } from '../../testing/TestData.js';
This needs to be switched to IndexedDB before the due date. Is that happening in another PR? That's what most people have been doing

2024-11-12 19:40 UTC, hungumass commented on front-end/src/components/LogViewComponent/LogViewComponent.js
> +    heartIcon.classList.add("favorite-icon");
Should be good now!

2024-11-12 20:20 UTC, sophia-hubscher requested changes
I noted a few changes. Even with those, I don't think you're properly waiting for things to load before rendering, so I would add a fix for that too

2024-11-12 20:20 UTC, sophia-hubscher commented on front-end/src/testing/TestData.js
The outfits in this file are messing up testing. I think it's because the date format is wrong. I would either change the dates to match whatever the output of `new Date()` is _or_ (probably a better option), you can remove the date fields from the test data, and rearrange, the outfit data model constructor as follows:

```
    constructor(outfit_id, user_id, wardrobe_item_ids, note, occasion, seasons, created_at = new Date(), updated_at = new Date()) {
```

That way, the test data could just be like this:

```outfits.push(
    new OutfitEntry(
      "1",
      "user1",
      ["item1", "item2"],
      "First outfit!",
      "casual",
      ["Winter"]
    )
  );
  ```

2024-11-12 20:20 UTC, sophia-hubscher commented on front-end/src/testing/TestData.js
> +  const wardrobeService = new OutfitRepositoryService();
should be `outfitService`

2024-11-12 20:47 UTC, nhan0504 approved these changes
Just some nit. Otherwise, Sophia have mentioned everything

2024-11-13 01:55 UTC, hungumass commented on front-end/src/testing/TestData.js
I don't think the date should matter here, and everything else should be fine, lmk if there is anything wrong

2024-11-13 03:56 UTC, AshleyMcN commented on front-end/src/components/LogViewComponent/LogViewComponent.js
> +import { getTestOutfits,getTestWardrobeItems } from '../../testing/TestData.js';
There is an issue with what the test data for loadOutfitItems() uses and what the data model is expecting. If in the test data, you replace all of the outfits created at and updated at string with "new Date()", the loadOutfitItems() should work for loading in test indexdb data.
![image](https://github.com/user-attachments/assets/fc58e685-06e5-4045-91fb-0ebca361924a)

2024-11-13 03:59 UTC, AshleyMcN commented on front-end/src/testing/TestData.js
Without removing those strings for the date, you will not be able to load in test data to your local indexDB storage so you won't be able to test the log page with indexdb. Anyway, for future use, it would be good to update that file and remove the dates since the test data is wrong.

2024-11-14 14:02 UTC, sophia-hubscher approved these changes
LGTM!

2024-11-14 14:02 UTC, merged