Add LogAddItem and LogDeleteItem components with event handling
nhan0504/CS326 pull request #61
Opened 2024-11-16 20:10 UTC by KhanhLeBigWow

## Summary
This PR introduces two new features to the `LogViewComponent`:
- **LogAddItem:** Enables users to add items from their wardrobe to the current day's outfit log.
- **LogDeleteItem:** Allows users to remove outfits from the outfit log.

### Key Changes:
1. **New Components:**
   - `LogAddItem.js` and `LogDeleteItem.js`:
     - Implemented modular components for adding and deleting items in the outfit log.
     - Integrated with `WardrobeRepositoryService` and `OutfitRepositoryService` for data handling.
     - Utilized event publishing (`Events.OutfitUpdated`, `Events.OutfitDeleted`) to communicate changes.

2. **LogViewComponent Adjustments:**
   - Subscribed to new events (`Events.OutfitUpdated`, `Events.OutfitDeleted`) to refresh the outfit list dynamically.
   - Ensured compatibility with the new components and maintained existing functionality.

3. **Sequence Diagram Updates:**
   - Documented the operational flow for `LogAddItem` and `LogDeleteItem` using sequence diagrams for better understanding.

## How It Works:
- **LogAddItem:** Opens a modal to select items from the wardrobe. On confirmation, the selected items are added to the current outfit and saved to IndexedDB.
- **LogDeleteItem:** Deletes an outfit from IndexedDB and updates the UI dynamically.

## Testing:
- Added manual tests to verify:
  - Adding items to the outfit log.
  - Deleting outfits from the outfit log.
  - Event propagation and UI updates in `LogViewComponent`.

## Notes for Reviewers:
- Please test the following scenarios:
  1. Adding multiple items to today's outfit log.
  2. Deleting an outfit from the log page.
  3. Verifying that changes persist in IndexedDB across sessions.
- Look for any unintended side effects on the `LogViewComponent` or `WardrobeRepositoryService`.

2024-11-16 20:36 UTC, AshleyMcN requested changes

2024-11-16 20:36 UTC, AshleyMcN commented on front-end/src/components/LogViewComponent/LogViewComponent.js
> +    this.subscribe(Events.OutfitUpdated, () => {
The code doesn't run because there is an error that "this.subscribe is not a function"

2024-11-17 16:14 UTC, sophia-hubscher commented on front-end/src/components/LogViewComponent/LogViewComponent.js
> +    this.subscribe(Events.OutfitUpdated, () => {
I made a new branch with fixes for this

2024-11-17 21:04 UTC, AshleyMcN approved these changes

2024-11-17 21:04 UTC, merged