Set up back-end
nhan0504/CS326 pull request #94
Opened 2024-11-30 06:54 UTC by anishap16

Sets up functionality for OutfitEntry and WardrobeItem entities by implementing models, controllers, and routes. Models are created with in-memory and SQLite support, and controllers manage CRUD operations. Routes are organized under /v1/outfits and /v1/items

2024-12-01 00:03 UTC, nhan0504 requested changes
Left a few comments. Otherwise LGTM!

2024-12-01 00:03 UTC, nhan0504 commented on back-end/Server.js
> +    this.app.use("/v1/outfits", OutfitRoutes);
I think this will prefix all routes in `OutfitRoutes` with "/v1/outfits" so the endpoint will be "/v1/outfits/outfits"

2024-12-01 00:03 UTC, nhan0504 commented on back-end/Server.js
> +    this.app.use("/v1/items", ItemRoutes);
I think this will prefix all routes in `ItemRoutes` with "/v1/items" so the endpoint will be "/v1/items/items"

2024-12-01 00:03 UTC, nhan0504 commented on back-end/Server.js
> +  start(port = 3000) {
Isn't the front end running on port 3000? I think we should use a different port

2024-12-01 03:11 UTC, anishap16 commented on back-end/source/model/SQLiteWardrobeModel.js
> +    allowNull: true,
made it required just in case!

2024-12-01 03:17 UTC, anishap16 commented on back-end/source/model/SQLiteWardrobeModel.js
> +    return await WardrobeItem.create(item);
that's a good idea, thank you!

2024-12-02 18:56 UTC, nhan0504 approved these changes
LGTM!

2024-12-02 18:56 UTC, merged